debionetwork/debio-genetic-analyst-ui

.github/workflows/analyzer.yml
.github/workflows/deployer.yml
.github/workflows/tester.yml
.maintain/docker/Dockerfile
.maintain/docker/nginx/nginx.conf

ci: fix permissions

---

src/views/Dashboard/GeneticAnalyst/Orders/Details.vue

- N/A
- Improvement several ui/ux experiences
-

fix: Add code improvement

---

src/views/LandingPage/GenerateAccount/SetPassword.vue
src/views/LandingPage/SignIn/ChangePassword.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1976
- Fix failing Recaptcha components.

fix: recaptcha.

---

src/common/components/NavigationDrawer.vue
src/common/lib/route-guard.js
src/views/LandingPage/GenerateAccount/RegistrationSuccessful.vue
src/views/LandingPage/SignIn/index.vue
src/views/NotFound.vue

- N/A
- Update mismatch route
- Remove trailing spaces
-

fix: Mismatch route and remove trailing spaces

---

src/views/Dashboard/GeneticAnalyst/Orders/Details.vue

- N/A
- Improvement several ui/ux experiences
- Fix undefined metadata
-

refactor: Update several ui/ux experiences

---

src/store/substrate/index.js
src/views/Dashboard/GeneticAnalyst/Home/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1928
- Add dynamic verification status
-

[DBIO-1928] feat: Verification status (Dynamic) #358

---

src/common/lib/pinata/index.js
src/views/Dashboard/GeneticAnalyst/Home/index.vue
src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
tests/unit/views/Dashboard/GeneticAnalyst/Home/index.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1929
- https://blocksphere2020.atlassian.net/browse/DBIO-2095
- Update GA unit testing with the verification status
- Fix can't process orders
-

[DBIO-1929] tests: Update GA unit testing

---

src/common/lib/polkadot-provider/command/genetic-analyst/services.js
src/router/routes/geneticAnalyst.js
src/store/substrate/index.js
src/views/Dashboard/GeneticAnalyst/Services/index.vue
tests/unit/views/Dashboard/GeneticAnalyst/Services/index.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-2171
- https://blocksphere2020.atlassian.net/browse/DBIO-2172
- create ga service list
- create unit test for render ga service list
- create command for ga services pallate
- complete delete ga service feature
-

[DBIO-2171, DBIO-2172] feat: create ga service list and unit test 

---

src/common/lib/api/index.js
src/views/Dashboard/GeneticAnalyst/Layout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2084
- handle general error from API
-

[DBIO-2084] feat: handle general error from API

---

.maintain/install-hooks.sh
package.json
tests/unit/crypt-worker.mock.js
tests/unit/ipfs-worker.mock.js
tests/unit/views/Dashboard/GeneticAnalyst/Orders/details.spec.js
tests/unit/views/Dashboard/GeneticAnalyst/layout.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-2153
- Git hooks.

feat: git hooks 

---

package.json
src/common/components/Dialog/SuccessDialogGeneral.vue
src/common/lib/api/customer/categories.js
src/common/lib/polkadot-provider/command/genetic-analyst/analysts.js
src/common/lib/polkadot-provider/command/genetic-analyst/qualifications.js
src/router/routes/geneticAnalyst.js
src/views/Dashboard/GeneticAnalyst/Account/ConfirmationDialog.vue
src/views/Dashboard/GeneticAnalyst/Account/index.vue
tests/unit/views/Dashboard/GeneticAnalyst/Account/confirmation.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1931
- https://blocksphere2020.atlassian.net/browse/DBIO-1933
- https://blocksphere2020.atlassian.net/browse/DBIO-1936
- https://blocksphere2020.atlassian.net/browse/DBIO-1938
- https://blocksphere2020.atlassian.net/browse/DBIO-1932
- https://blocksphere2020.atlassian.net/browse/DBIO-1934
- https://blocksphere2020.atlassian.net/browse/DBIO-1937
- https://blocksphere2020.atlassian.net/browse/DBIO-1939
- edit feature genetic analyst profile
- add edit certificate
- set availability
- unstake GA profile
- unit testing GA profile
-

[DBIO-1931, DBIO-1933, DBIO-1936, DBIO-1938, DBIO-1932, DBIO-1934, DBIO-1937, DBIO-1939] feat: genetic analyst profile

---

src/common/lib/api/index.js
src/views/Dashboard/GeneticAnalyst/Layout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2084
- update single line condition & watch query
-

[DBIO-2084] fix: update single line condition & watch query

---

src/views/Dashboard/GeneticAnalyst/Services/index.vue
tests/unit/views/Dashboard/GeneticAnalyst/Services/index.mock.js
tests/unit/views/Dashboard/GeneticAnalyst/Services/index.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-2143
- Functional test for the `methods`, `mounted`, and `watch` functions on each page.

tests: full unit test example

---

package-lock.json
src/common/components/Navbar.vue

fix: fix debio balance on navbar

---

src/common/lib/pinata-proxy.js

- N/A
- Update the pinata gateway link with ENV
-

refactor : Update the pinata gateway link with ENV

---

src/common/lib/api/index.js

- 
- update condition handle error from api
-

fix: update condition handle error from api

---

src/common/components/Orders/OrderList.vue
src/common/lib/pinata-proxy.js
src/store/genetic-data.js
src/views/Dashboard/GeneticAnalyst/Home/index.vue
src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
src/views/Dashboard/GeneticAnalyst/Orders/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2230
- N/A
- Add loading popup
-

feat: add loading spinner on upload

---

.github/CODEOWNERS
package.json
src/common/lib/pinata-proxy.js
src/views/Dashboard/GeneticAnalyst/Account/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2424
- fix add/edit certificate & enhance function name from polkadot-povider lib
-

fix: enhance GA account

---

src/common/components/Orders/OrderList.vue
src/views/Dashboard/GeneticAnalyst/Orders/Details.vue

- N/A
- Temp typo from backend
-

fix: GA orders lists

---

src/common/components/Orders/OrderList.vue
src/views/Dashboard/GeneticAnalyst/Home/index.vue
src/views/Dashboard/GeneticAnalyst/Orders/index.vue

- N/A
- handle none trakingId
-

fix: handle trackingId if return <none>

---

src/views/Dashboard/GeneticAnalyst/Account/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1933
- remove phone code
- fix validation & limit char
-

fix: validation & limit char

---

src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
src/views/Dashboard/GeneticAnalyst/Orders/index.vue

- N/A
- Fix genetic result upload
-

fix: genetic result upload

---

src/views/Dashboard/GeneticAnalyst/Account/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1933
- add max birth of date
- fix load data after save

fix: max birth of date & handle save

---

src/views/Dashboard/GeneticAnalyst/Account/index.vue

- N/A
- enhance GA account upload
-

fix : Upload GA account

---

src/common/components/Account/InformationForm.vue
src/common/components/Dialog/CertificateDialog.vue
src/common/components/Dialog/DeleteServiceDialog.vue
src/common/components/Dialog/InsufficientBalanceDialog.vue
src/common/components/Dialog/StakeDialog.vue
src/common/components/Dialog/SuccessDialogGeneral.vue
src/common/components/NavigationDrawer.vue
src/common/components/Service/AddService.vue
src/common/lib/polkadot-provider/command/genetic-analyst/index.js
src/common/lib/polkadot-provider/command/genetic-analyst/qualification.js
src/common/lib/route-guard.js
src/router/routes/geneticAnalyst.js
src/router/routes/registration.js
src/store/substrate/index.js
src/views/Dashboard/GeneticAnalyst/Account/index.vue
src/views/Dashboard/GeneticAnalyst/Home/Unverified.vue
src/views/Dashboard/GeneticAnalyst/Layout.vue
src/views/Dashboard/GeneticAnalyst/Registration/AccountInformation.vue
src/views/Dashboard/GeneticAnalyst/Registration/AddService.vue
src/views/Dashboard/GeneticAnalyst/Services/AddService.vue
src/views/Dashboard/GeneticAnalyst/Services/EditService.vue
src/views/Dashboard/GeneticAnalyst/Services/index.vue
tests/unit/views/Dashboard/GeneticAnalyst/Services/index.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-1920
- https://blocksphere2020.atlassian.net/browse/DBIO-1915
- https://blocksphere2020.atlassian.net/browse/DBIO-2164
- https://blocksphere2020.atlassian.net/browse/DBIO-2165
- feature GA regist step 1 & 2
- feature GA add service
- feature GA edit service
-

feat: GA registration page

---

package.json
src/views/Dashboard/GeneticAnalyst/Orders/Details.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2576
- Fix typo.
- Update polkadot provider package.

fix: typo and update polkadot provider package

---

.github/workflows/analyzer.yml
.github/workflows/builder.yml
.github/workflows/deployer.yml
.github/workflows/tester.yml

- N/A
- ci: use wlif for gcr auth
-

ci: use wlif for gcr auth

---

src/common/lib/pinata-proxy.js

- N/A
- Add required metadata to Pinata for bulk delete documents that are within the scope of development
- Please frontend add new ENV https://blocksphere2020.atlassian.net/wiki/spaces/DBIO/pages/33063034/Frontend+ENV

refactor: Add required file document

---

src/common/components/Dialog/SuccessDialogGeneral.vue
src/common/constants/error-messages.js
src/common/constants/rules.js
src/views/Dashboard/GeneticAnalyst/Account/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2538
- https://blocksphere2020.atlassian.net/browse/DBIO-2539
- add linkedin profile link
- update redirect after edit GA profile
-

feat: add linkedin profile link

---

src/common/components/Account/InformationForm.vue
src/common/components/Dialog/CertificateDialog.vue
src/common/components/Dialog/InsufficientBalanceDialog.vue
src/common/components/Dialog/StakeDialog.vue
src/common/components/Service/AddService.vue
src/common/lib/route-guard.js
src/router/routes/registration.js
src/views/Dashboard/GeneticAnalyst/Registration/AddService.vue
src/views/Dashboard/GeneticAnalyst/Services/AddService.vue
src/views/Dashboard/GeneticAnalyst/Services/EditService.vue
tests/unit/common/components/Service/AddService.spec.js
tests/unit/views/Dashboard/GeneticAnalyst/Registration/AccountInformation.spec.js
tests/unit/views/Dashboard/GeneticAnalyst/Registration/AddService.spec.js
tests/unit/views/Dashboard/GeneticAnalyst/Services/AddService.spec.js
tests/unit/views/Dashboard/GeneticAnalyst/Services/EditService.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-2166
- https://blocksphere2020.atlassian.net/browse/DBIO-1921
- https://blocksphere2020.atlassian.net/browse/DBIO-1920
- https://blocksphere2020.atlassian.net/browse/DBIO-1916
- https://blocksphere2020.atlassian.net/browse/DBIO-2164
- Fix some defect GA regist
- unit testing GA regist step 2
- unit testing Add Service
- unit testing Edit Service
-

fix: defect GA regist

---

src/views/LandingPage/GenerateAccount/GenerateMnemonic/index.vue
src/views/LandingPage/GenerateAccount/VerifyMnemonic/index.vue
src/views/LandingPage/GenerateAccount/index.vue
src/views/LandingPage/LandingPagePopUp.vue
src/views/LandingPage/Layout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2634
- fix wording on generate account
- n/a

fix: wording and styling on generate accout

---

src/views/Dashboard/GeneticAnalyst/Orders/Details.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2635
- Upload document upload result flow
-

refactor: Upload document flow

---

src/common/components/Account/InformationForm.vue
src/views/Dashboard/GeneticAnalyst/Registration/AccountInformation.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2641
- add linkedin field on regist page
-

feat: add linkedin field on regist page

---

src/common/components/Dialog/WarningDialog.vue
src/views/Dashboard/GeneticAnalyst/Account/index.vue
src/views/Dashboard/GeneticAnalyst/Services/index.vue
tests/unit/views/Dashboard/GeneticAnalyst/Services/index.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-2605
- https://blocksphere2020.atlassian.net/browse/DBIO-2593
- create global component for dialog warning/alert
- add validation in delete service when still have active order
- add validation in unstake & set unavailable when still have active order
-

feat : Active order validation

---

src/common/components/Service/AddService.vue
src/views/Dashboard/GeneticAnalyst/Services/EditService.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2165
- format price fromWei on edit service
- handle currency by props
-

fix: format price & value

---

src/common/components/Account/InformationForm.vue
src/common/components/Dialog/CertificateDialog.vue
src/common/components/Service/AddService.vue
src/common/lib/pinata-proxy.js
src/views/Dashboard/GeneticAnalyst/Account/index.vue
src/views/Dashboard/GeneticAnalyst/Orders/Details.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2661
- Add file size description
-

feat: Add file size description

---

src/views/Dashboard/GeneticAnalyst/Orders/Details.vue

- N/A
- Fix ga error download
-

fix: GA download file

---

src/common/lib/metamask/index.js
src/common/styles/mixins.sass
src/views/Dashboard/GeneticAnalyst/Layout.vue
src/views/LandingPage/GenerateAccount/index.vue
src/views/LandingPage/LandingPagePopUp.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-1262
- https://blocksphere2020.atlassian.net/browse/DBIO-2634
- add pop up to switch network to mainet / testnet
- adjust layout styling on generate account
- n/a

feat: add switch network to mainnet / testnet

---

src/common/components/Navbar.vue
src/router/routes/geneticAnalyst.js

- https://blocksphere2020.atlassian.net/browse/DBIO-2613
- remove /genetic-analyst path
-

refactor: remove /genetic-analyst path

---

src/common/components/Service/AddService.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2717
- enhance service price validation
-

fix: service price validation

---

package-lock.json
package.json
src/views/Dashboard/GeneticAnalyst/Orders/Details.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2521
- Update version ui-component
- Update filesize validation
-

fix: GA image and file size

---

src/common/lib/route-guard.js
src/router/routes/generateAccount.js
src/views/LandingPage/GenerateAccount/RegistrationSuccessful.vue
src/views/LandingPage/LandingPagePopUp.vue
src/views/LandingPage/SignIn/ChangePassword.vue
src/views/LandingPage/index.vue
tests/unit/views/LandingPage/GenerateAccount/registration-successful.spec.js

- https://blocksphere2020.atlassian.net/browse/DBIO-2646
- adjust wording on set `registrationSuccessful.vue`
- fix routes
- adjust wording style to figma
-

feat: adjust wording on set/change password

---

src/common/lib/route-guard.js
src/router/routes/geneticAnalyst.js

- https://blocksphere2020.atlassian.net/browse/DBIO-2726
- https://blocksphere2020.atlassian.net/browse/DBIO-2663
- fix routes
- add wording on generate account
- n/a

fix: wrong routes on genetic-analyst login and registration

---

src/common/lib/route-guard.js
src/router/routes/geneticAnalyst.js
src/views/LandingPage/GenerateAccount/GenerateMnemonic/index.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2663
- add wording on generate account
- n/a

feat: add wording on generate account

---

src/store/substrate/index.js

- N/A
- Update validation event
-

fix: Event not show

---

.github/workflows/analyzer.yml
.github/workflows/builder.yml
.github/workflows/create-tags.yml
.github/workflows/deployer.yml
.github/workflows/release.yml
.github/workflows/update-version.yml

- N/A
- update version automation
- code formatting
- Endpoint:
- Scheduler:
- Listener:

ci: update version & formatting

---

src/views/Dashboard/GeneticAnalyst/Orders/Details.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2794
- N/A
- Update fix GA result upload
-

fix: GA upload result

---

src/views/Dashboard/GeneticAnalyst/Registration/AccountInformation.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2718
- convert date of birth to millisecond
-

fix: DoB convert to millisecond

---

.github/workflows/create-tags.yml

- N/A
- fix action permission
-

ci: fix action permission

---

.github/workflows/create-tags.yml

Reverts debionetwork/debio-genetic-analyst-ui#71

ci: revert "fix action permission"

---

src/views/Dashboard/GeneticAnalyst/Layout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2825
- remove switch network on Layout.vue
- should be added on each specific event if needed in the future

fix: remove switch network

---

src/router/routes/geneticAnalyst.js
src/views/Dashboard/GeneticAnalyst/Layout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2810
- update wording orders in menu
-

feat: update wording orders in menu

---

package-lock.json
package.json

- N/A
- bump version to 1.0.6
-

chore: bump version to 1.0.6

---

package-lock.json
package.json
src/common/components/Navbar.vue
src/views/Dashboard/GeneticAnalyst/Layout.vue
src/views/LandingPage/SignIn/ChangePassword.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2651
- add wallet from state on singin/changePassword
- n/a

fix: clear account and bump version 1.0.7

---

package-lock.json
package.json

- N/A
- Update polkadot-provider version
-

feat: Update polkadot-provider version

---

src/common/lib/route-guard.js

- https://blocksphere2020.atlassian.net/browse/DBIO-2847
- https://blocksphere2020.atlassian.net/browse/DBIO-2953
- fix condition route guard 
-

fix: route guard check account status

---

src/common/components/Service/AddService.vue
src/views/Dashboard/GeneticAnalyst/Orders/Details.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2988
- rename expected to maximum
-

fix: change from Expected to Maximum

---

src/common/lib/utils/env.js

- https://blocksphere2020.atlassian.net/browse/DBIO-ISSUE_NUMBER
- N/A
- fix linter error
-

fix: linter error

---

src/common/components/Dialog/StakeDialog.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2698
- fix staking amount on GA
-

fix: error on staking GA

---

src/store/substrate/index.js
src/views/Dashboard/GeneticAnalyst/Layout.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-2947
- fix fetch notification
-

fix: fetch notification

---

src/common/lib/notification.js
src/common/lib/string-format.js

- https://blocksphere2020.atlassian.net/browse/DBIO-ISSUE_NUMBER
- N/A
- add fmtReferenceFromHex to string-format file
-

feat: add fmtReferenceFromHex to string-format file

---

src/common/components/Service/AddService.vue

- https://blocksphere2020.atlassian.net/browse/DBIO-3006
- Add USN & USDT on currency list
-

feat: add USN and USDT on currency list

---

.maintain/docker/entrypoint.sh

ci: fixed docker entrypoint
- https://blocksphere2020.atlassian.net/browse/DBIO-ISSUE_NUMBER

ci: fixed docker entrypoint

---

.github/workflows/deployer.yml
.maintain/docker/entrypoint.sh
README.md

ci: cleanup ssh tunneling

---

package-lock.json
src/common/components/Navbar.vue
src/common/components/Orders/OrderList.vue
src/common/components/Service/AddService.vue
src/common/lib/balance-format.js
src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
src/views/Dashboard/GeneticAnalyst/Registration/AddService.vue
src/views/Dashboard/GeneticAnalyst/Services/AddService.vue
src/views/Dashboard/GeneticAnalyst/Services/EditService.vue
src/views/Dashboard/GeneticAnalyst/Services/index.vue
tests/unit/common/components/Service/AddService.spec.js
tests/unit/views/Dashboard/GeneticAnalyst/Account/confirmation.spec.js
tests/unit/views/Dashboard/GeneticAnalyst/Account/index.spec.js
tests/unit/views/Dashboard/GeneticAnalyst/Home/index.spec.js
tests/unit/views/Dashboard/GeneticAnalyst/Orders/details.spec.js
tests/unit/views/Dashboard/GeneticAnalyst/Registration/AccountInformation.spec.js
tests/unit/views/Dashboard/GeneticAnalyst/Registration/AddService.spec.js
tests/unit/views/Dashboard/GeneticAnalyst/Services/AddService.spec.js
tests/unit/views/Dashboard/GeneticAnalyst/Services/EditService.spec.js
tests/unit/views/Dashboard/GeneticAnalyst/Services/index.spec.js
tests/unit/views/Dashboard/GeneticAnalyst/layout.spec.js

- handle decimal for usdt
- https://blocksphere2020.atlassian.net/browse/DBIO-3127

feat: handle decimal for usdt and remove dbio from currency list

---

src/common/lib/api/genetic-analyst/orders.js
src/views/Dashboard/GeneticAnalyst/Registration/AddService.vue

- add endpoint email/registered-genetic-analyst/{genetic_analyst_id}
- add logic to send email when GeneticAnalystStakeSuccessful
- https://blocksphere2020.atlassian.net/browse/DBIO-3027

feat: implement send email for GA registration & verification

---

src/common/components/Service/AddService.vue
src/common/lib/api/customer/debio-balance.js
src/views/Dashboard/GeneticAnalyst/Registration/AddService.vue

- remove USN from genetic analyst
- https://blocksphere2020.atlassian.net/browse/DBIO-3153

feat: remove USN

---

src/common/components/Service/AddService.vue

- add conversion in add service
- https://blocksphere2020.atlassian.net/browse/DBIO-3153

feat: add conversion

---

src/common/components/Service/AddService.vue

- add copywriting below service price
- https://blocksphere2020.atlassian.net/browse/DBIO-3142

feat: add copywriting below service price

---

src/common/components/Dialog/StakeDialog.vue

- remove "," in minimum staking before
- https://blocksphere2020.atlassian.net/browse/DBIO-3191

fix: stake ga registration

---

src/common/components/Navbar.vue
src/common/components/Service/AddService.vue
src/common/lib/balance-format.js
src/views/Dashboard/GeneticAnalyst/Registration/AddService.vue
src/views/Dashboard/GeneticAnalyst/Services/AddService.vue
src/views/Dashboard/GeneticAnalyst/Services/EditService.vue
src/views/Dashboard/GeneticAnalyst/Services/index.vue

- change payment from USDT to USDT.e
- https://blocksphere2020.atlassian.net/browse/DBIO-3245

feat: change payment from USDT to USDT.e

---

src/views/Dashboard/GeneticAnalyst/Orders/Details.vue

- fix USDTE on Detail Order Page
- https://blocksphere2020.atlassian.net/browse/DBIO-3245

fix: USDTE on Detail Order Page

---

src/assets/health-professional-banner.svg
src/common/components/Account/InformationForm.vue
src/common/components/Dialog/RegistrationSentDialog.vue
src/common/components/Dialog/SuccessDialogGeneral.vue
src/common/components/HealthProfessionalBanner.vue
src/router/routes/genetic-analyst.js
src/router/routes/health-professional.js
src/store/auth.js
src/views/Dashboard/GeneticAnalyst/Registration/AccountInformation.vue
src/views/Dashboard/HealthProfessional/Account/index.vue
src/views/Dashboard/HealthProfessional/Home/index.vue

- add health professional dashboard page
- add registration page
- add logic to view and edit account
- https://blocksphere2020.atlassian.net/browse/DBIO-3214
- https://blocksphere2020.atlassian.net/browse/DBIO-3228
- https://blocksphere2020.atlassian.net/browse/DBIO-3227

feat: add dashboard and registration pages (ui-only)

---

src/common/components/Orders/OrderList.vue

- fix render USDTE on order list
- https://blocksphere2020.atlassian.net/browse/DBIO-3245

fix: render USDTE on order list

---

src/common/components/Navbar.vue
src/views/Dashboard/HealthProfessional/Home/index.vue

- add install polkadot pop up
- enhance export json keystore file in wallet
- https://blocksphere2020.atlassian.net/browse/DBIO-3265
- https://blocksphere2020.atlassian.net/browse/DBIO-3271

feat: add install polkadot pop up

---

src/common/components/Account/InformationForm.vue
src/common/components/Account/dummySpecialization.json
src/common/components/Orders/OrderList.vue
src/views/Dashboard/GeneticAnalyst/Home/Unverified.vue
src/views/Dashboard/HealthProfessional/Account/index.vue
src/views/Dashboard/HealthProfessional/Home/index.vue

- enhance medical provider registration form
- fix typo Daogenic to Daogenics
- https://blocksphere2020.atlassian.net/browse/DBIO-3214

feat: medical provider registration form enhancement

---

src/common/components/Account/InformationForm.vue

- add tooltip on privacy setting
- https://blocksphere2020.atlassian.net/browse/DBIO-3214

feat: add tooltip on privacy setting

---

src/common/components/Account/InformationForm.vue
src/views/Dashboard/GeneticAnalyst/Account/index.vue

change category to specialization

fix: change category to specialization

---

src/common/components/Account/InformationForm.vue
src/views/Dashboard/GeneticAnalyst/Account/index.vue
src/views/Dashboard/GeneticAnalyst/Registration/AddService.vue

- fix get specialization (change back specialization to category)
- fix add new service
-

fix: ga-registration

---

src/common/components/Account/InformationForm.vue
src/views/Dashboard/HealthProfessional/Account/index.vue

- fix logic when generate and check username
- add new field for specialization to diff it with category
- https://blocksphere2020.atlassian.net/browse/DBIO-3250

fix: checkUsername and add new fields for specialozation

---

src/common/lib/api/health-professional/myriad.js
src/views/Dashboard/HealthProfessional/Home/index.vue
src/views/NoAccessMobile.vue

- change wording on mobile view
- https://blocksphere2020.atlassian.net/browse/DBIO-3111

feat: enhance mobile view

---

src/App.vue
src/common/components/Account/InformationForm.vue
src/common/components/Dialog/InsufficientBalanceDialog.vue
src/common/lib/api/health-professional/index.js
src/common/lib/api/health-professional/myriad.js
src/common/lib/api/health-professional/registration-email.js
src/views/Dashboard/HealthProfessional/Account/index.vue
src/views/Dashboard/HealthProfessional/Home/index.vue
src/views/Dashboard/HealthProfessional/Layout.vue
src/views/NoAccessMobile.vue

- enhance mobile view
- fix insufficient dialog's name
- remove logs
- fix api register and auth
- add "unverified" at temporary role 
- add send registration email
- fix dashboard menu and show staking dialog
- https://blocksphere2020.atlassian.net/browse/DBIO-3111
- https://blocksphere2020.atlassian.net/browse/DBIO-3250

fix: registrahtion hp enhancement

---

src/common/components/Account/InformationForm.vue
src/views/Dashboard/HealthProfessional/Home/index.vue

- fix render total opinion
- fix role and specialization
- https://blocksphere2020.atlassian.net/browse/DBIO-3250

fix: hp dashboard

---

src/views/Dashboard/HealthProfessional/Home/index.vue

- fix some wordings
- fix fetch unlocked content

fix: some wordings and fetch unlocked content

---

src/views/Dashboard/HealthProfessional/Home/index.vue

- change amoutn to boolean on unlocked content column

fix: change amount to boolean on unlocked content column

---

src/common/lib/api/health-professional/myriad.js

- adjust api myriadContents (add page and limit params)

fix: adjust api myriadContents

---

src/common/lib/api/health-professional/myriad.js

fix: adjust api myriad contents

---

src/common/components/Account/InformationForm.vue
src/common/lib/api/health-professional/specialization.js

- add API for get health professional roles
- N/A

feat: add API for get health professional roles

---

src/views/Dashboard/HealthProfessional/Account/index.vue

- add function to handle short hex nonce

fix: handle short nonce

---

src/views/Dashboard/GeneticAnalyst/Services/EditService.vue

- fix currency format in updateGeneticAnalystService
- N/A

fix: currency format in updateGeneticAnalystService

---

src/common/components/Service/AddService.vue
src/views/Dashboard/GeneticAnalyst/Services/AddService.vue
src/views/Dashboard/GeneticAnalyst/Services/EditService.vue

fix: add quality control price to genetic analysis service

---

src/common/lib/ipfs/crypt-worker/encrypt-worker-file.js
src/views/Dashboard/GeneticAnalyst/Orders/Details.vue

fix: Genetic Analyst upload

---

src/common/constants/rules.js
src/common/lib/ipfs/crypt-worker/encrypt-worker-file.js
src/views/Dashboard/GeneticAnalyst/Orders/Details.vue

fix: update size

---

src/views/Dashboard/GeneticAnalyst/Services/AddService.vue
src/views/Dashboard/GeneticAnalyst/Services/EditService.vue

fix: add link to description

---

src/common/components/Service/AddService.vue
src/views/Dashboard/GeneticAnalyst/Services/AddService.vue
src/views/Dashboard/GeneticAnalyst/Services/EditService.vue
src/views/Dashboard/GeneticAnalyst/Services/index.vue

fix: Edit page show incorrect information

---

src/views/Dashboard/GeneticAnalyst/Orders/Details.vue

fix: chunk size shown

---

src/views/Dashboard/HealthProfessional/Home/index.vue

fix: redirect to myriad button

---

src/views/Dashboard/HealthProfessional/Home/index.vue

fix: window open not working

---

src/views/Dashboard/HealthProfessional/Home/index.vue

fix: add hyperlink in case button redirect failed

---

src/views/Dashboard/GeneticAnalyst/Services/AddService.vue
src/views/Dashboard/GeneticAnalyst/Services/EditService.vue
src/views/Dashboard/GeneticAnalyst/Services/index.vue
tests/unit/views/Dashboard/GeneticAnalyst/Services/index.spec.js

fix: turn string into ipfs txt file
